export const LOAD_ACTIVITIES_SUCCESS = "LOAD_ACTIVITIES_SUCCESS";
export const ACTIVITY_RECEIVED_FROM_SOCKET = "ACTIVITY_RECEIVED_FROM_SOCKET";
export const ACTIVITIES_UPDATED = "ACTIVITIES_UPDATED";
